### ISSUE TITLE
Connection between Navigation Timing 2 and Performance Timeline is underdefined

### ISSUE THREAD

**Issue by plehegar** [w3c/navigation-timing#1]
[[
I see nothing anywhere in
https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming2/Overview.html
that creates instances of PerformanceNavigationTiming. Should there be
something? There are examples that claim that such instances should
exist and that performance.getEntriesByType should be able to find them,
but I see no normative basis for that claim.
]]
http://lists.w3.org/Archives/Public/public-web-perf/2014Jun/0015.html
(and follow up)

**Comment by toddreifsteck** [comment]
Internet Explorer implements the following but they do not appear in normative text--
performance.getEntriesByName('document') returns navigation timings.
performance.getEntriesByType('navigation') returns navigation timings.

It appears that the intent of the spec was to support accessing the updated PerformanceNavigationTiming via these 2 methods and to keep the original performance.timing returning PerformanceTiming.

Given that, we should update the normative text.

@igrigorik @bzbarsky What do you think?

**Comment by igrigorik** [comment]
In the context of the [new redirect logic](https://lists.w3.org/Archives/Public/public-web-perf/2015Feb/0059.html) we've been discussing.. I think this becomes a requirement, and I'll have to fix this as part of that pull.

**Comment by bzbarsky** [comment]
@toddreifsteck Actually normatively defining when PerformanceNavigationTiming instances are created and added to the performance timeline sounds reasonable, yes.  That's what I asked for in that thread 9 months ago.

Once you do that, I think the getEntriesByName/getEntriesByType behavior falls out automatically.

**Comment by plehegar** [comment]
First attempt at https://github.com/w3c/navigation-timing/pull/36

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/navigation-timing/pull/36, closing.
