### ISSUE TITLE
workerStart should be clearly defined as applicable to the last SW

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#100]
Spinoff from https://github.com/w3c/resource-timing/issues/118

Currently, in the case of multiple redirects, each with it's own SW, it's not clear which worker start time should be reflected in `workerStart`. We should clarify that it's either the last SW applicable, or the active SW of the final document. The latter seems to be a more consistent definition.

**Comment by nicjansma** [comment]
Addressed in #131.

Defined as the ServiceWorker startup time of the first request in the final same-origin redirect chain.

Scenarios (a.com and b.com have SWs, c.com does not)

1. `a.com -> b.com`: b.com's SW startup
2. `a.com -> b.com/1 -> b.com/2`: b.com/1 SW startup
3. `a.com -> b.com/1 -> a.com -> b.com/2`: b.com/2 SW startup
4. `a.com -> b.com/1 -> c.com -> b.com/2`: b.com/2 SW startup
5. `a.com -> b.com/1 -> c.com -> b.com/2 -> b.com/3`: b.com/2 SW startup
6. `a.com -> b.com -> c.com`: `0` (c.com does not have SW)

**Comment by noamr** [comment]
What does it mean to be "intercepted" by a SW? 
I read it as "the service worker captures the `FetchEvent`, sends out a new `fetch` and calls `respondWith` with that fetch".
Is my understanding correct? There is no current way for a SW to return a "redirect response" that is handled externally by FETCH or HTML.

In the above case the timing details of the "internal" fetch (the one initiated by the SW) are totally opaque to the caller of the external fetch (the navigation). Think of the SW in this case as a transparent proxy server of sorts, it knows its own timing but "hides" them from the client.

So any redirects that are a result of a `fetch()` call inside a SW would appear as timing info in the SW performance timeline but not as part of the navigation, and only the *external* SW (which would be the first to respond) would reports its `workerStart` to navigation timing.

**Comment by yoavweiss** [comment]
I think we typically refer to your first interpretation, but both seem valid.



> In the above case the timing details of the "internal" fetch (the one initiated by the SW) are totally opaque to the caller of the external fetch (the navigation). Think of the SW in this case as a transparent proxy server of sorts, it knows its own timing but "hides" them from the client.

At the same time, if we expose the workerStart time of an early redirect to the eventual document, which may be on a different origin, that could create a cross-origin leak. The final redirect is always same-origin with the document that would receive this info. In the case of NavigationTiming, the "navigation" is not a concept that gets any info, the committed document is. We need to keep that in mind.

**Comment by noamr** [comment]
> I think we typically refer to your first interpretation, but both seem valid.
> 
> > In the above case the timing details of the "internal" fetch (the one initiated by the SW) are totally opaque to the caller of the external fetch (the navigation). Think of the SW in this case as a transparent proxy server of sorts, it knows its own timing but "hides" them from the client.
> 
> At the same time, if we expose the workerStart time of an early redirect to the eventual document, which may be on a different origin, that could create a cross-origin leak. The final redirect is always same-origin with the document that would receive this info. In the case of NavigationTiming, the "navigation" is not a concept that gets any info, the committed document is. We need to keep that in mind.

I don't think this is a problem.
The scenario here, as I understand it, would be:
- A navigation occurs
- A SW captures the `FetchEvent`, and responds with the response from a new `fetch` to a different origin.
- The RT entry for that fetch in the SW performance timeline would have redirect timing info only if that different origin response had TAO
- The navigation timing entry would not have any redirect information

**Comment by noamr** [comment]
>  b) Origin A's SW fetches a resource from origin A, which redirects to B

That redirect is completely hidden from the document. As far as the document knows, the document is in origin (A). Only the SW knows that something here is cross-origin at all. It's no different from the SW loading some cross-origin JSON and constructing the HTML for the navigation response by itself.
 
> c) Origin A's SW responds with a redirect response to origin B

This is like the second scenario in my [original comment](https://github.com/w3c/navigation-timing/issues/100#issuecomment-985990426) - "the service worker constructs a Response object with a redirect status".
In that scenario, `workerStart` would not be present as the navigation is involved in the redirect.

**Comment by noamr** [comment]
Note that if the worker in origin (B) constructs a redirect response, there is no mechanism for worker (A) to forward it to the navigation. Worker (A) only gets the response back after all the redirects are resolved (this is an important part of how FETCH works).

**Comment by yoavweiss** [comment]
> As far as the document knows, the document is in origin (A).

The document in is origin B in that case, and is oblivious to the initial redirect from origin A (modulo referrers).

> Only the SW knows that something here is cross-origin at all

Maybe we're not talking about the same scenario. I'm thinking about A's SW, fetching example.html, which then gets redirected (by the server, and below the SW in the network stack) to B/example.html.
A's SW will see an opaque response in that case, IIUC.

> This is like the second scenario in my [original comment](https://github.com/w3c/navigation-timing/issues/100#issuecomment-985990426) - "the service worker constructs a Response object with a redirect status".

Yeah.

> In that scenario, `workerStart` would not be present as the navigation is involved in the redirect.

I'm not sure I understand the connection.

**Comment by noamr** [comment]
> > As far as the document knows, the document is in origin (A).
> 
> The document in is origin B in that case, and is oblivious to the initial redirect from origin A (modulo referrers).
> 
> > Only the SW knows that something here is cross-origin at all
> 
> Maybe we're not talking about the same scenario. I'm thinking about A's SW, fetching example.html, which then gets redirected (by the server, and below the SW in the network stack) to B/example.html. A's SW will see an opaque response in that case, IIUC.

That opaque response is what would be brought back to the navigation, at least according to the spec.
The A->B redirect would be handled internally in the SW's fetch, and the navigation would not know anything about it, and should not, for example, set the address bar to the new address.
 
> > This is like the second scenario in my [original comment](https://github.com/w3c/navigation-timing/issues/100#issuecomment-985990426) - "the service worker constructs a Response object with a redirect status".
> 
> Yeah.
> 
> > In that scenario, `workerStart` would not be present as the navigation is involved in the redirect.
> 
> I'm not sure I understand the connection.

In the FETCH spec, `workerStart` is mapped to the response that comes after all the known redirects of that fetch are resolved. A constructed redirect from a worker is known to that FETCH, so it "trumps" the `workerStart`.

**Comment by yoavweiss** [comment]
> The A->B redirect would be handled internally in the SW's fetch, and the navigation would not know anything about it, and should not, for example, set the address bar to (B).

That seems odd. So a cross-origin redirect that modifies the URL bar without a SW would now not do that once a SW is introduced?

**Comment by noamr** [comment]
> > The A->B redirect would be handled internally in the SW's fetch, and the navigation would not know anything about it, and should not, for example, set the address bar to (B).
> 
> That seems odd. So a cross-origin redirect that modifies the URL bar without a SW would now not do that once a SW is introduced?

Yes, the SW fetch masks that redirect like a transparent proxy. The SW basically does the equivalent of CORS-fetching the HTML data and returns it to the browsing context as data stream (modified if it so chooses).

**Comment by noamr** [comment]
> > > The A->B redirect would be handled internally in the SW's fetch, and the navigation would not know anything about it, and should not, for example, set the address bar to (B).
> > 
> > 
> > That seems odd. So a cross-origin redirect that modifies the URL bar without a SW would now not do that once a SW is introduced?
> 
> Yes, the SW fetch masks that redirect like a transparent proxy. The SW basically does the equivalent of CORS-fetching the HTML data and returns it to the browsing context as data stream (modified if it so chooses).

OK, so the SW can override this by sending the fetch with redirect mode set to "manual", and forwarding the redirect to the caller. In this case, `workerState` of the original SW will not be available.

**Comment by noamr** [comment]
@yoavweiss I think this can be closed?

**Comment by noamr** [comment]
Closing, feel free to reopen.
