### ISSUE TITLE
Load event timings are not well-defined

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#101]
See https://github.com/whatwg/html/issues/4289
 /cc @bzbarsky @domenic @igrigorik

**Comment by noamr** [comment]
I think they are well defined now. Feel free to reopen if something is missing.

**Comment by bzbarsky** [comment]
@noamr could you please walk me through where and how the behavior is defined for the case I asked about in https://github.com/whatwg/html/issues/4289#issuecomment-454050631 ?

**Comment by bzbarsky** [comment]
Ah, it looks like the HTML spec now defines these directly (e.g. in "13.2.7 The end").  Yes, I agree, this looks much better than what we used to have.

**Comment by noamr** [comment]
> Ah, it looks like the HTML spec now defines these directly (e.g. in "13.2.7 The end").  Yes, I agree, this looks much better than what we used to have.

Exactly. Everything is defined explicitly and the "processing model" is purely informative.
