### ISSUE TITLE
supported entry types needs to be context aware

### ISSUE THREAD

**Issue by cvazac** [w3c/navigation-timing#102]
Companion issue to https://github.com/w3c/performance-timeline/issues/113.

[Relevant bits](https://github.com/w3c/navigation-timing/blob/7bdbdb5804ebe49994d81b22594de417d10e799a/index.html#L284).

**Comment by yoavweiss** [comment]
Discussed on the webperfwg call: most of this work needs to happen as part of performance timeline, which will then require small changes here. @cvazac volunteered to take a look at what that may look like.

**Comment by yoavweiss** [comment]
I believe we can close this is we changed to a registry model where registration doesn't have to be done as part of each spec. We also added a note reminding implementors of that.
