### ISSUE TITLE
Plenty of refs seem unhappy

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#109]
The spec now has 25 warnings about missing "data-cite"s, which at first glance don't seem to be missing.
@marcoscaceres - can you take a look?

/cc @plehegar

**Comment by marcoscaceres** [comment]
I’m back next week, but can take a look unless plh beats me to it.

**Comment by siusin** [comment]
I'll spend some time on these broken links this Wednesday :)
