### ISSUE TITLE
Can hitting enter on address bar to same URL be considered a navigation of type 'reload'?

### ISSUE THREAD

**Issue by npm1** [w3c/navigation-timing#116]
Suppose I do the following:
1. Load a website.
2. Click on the URL address bar.
3. Press Enter.

The same page is loaded. In Chrome, this is cached and treated as a reload. Does this count as a valid "reload operation" and thus can it be considered of NavigationType 'reload'? Or is this necessarily a navigation of type 'navigate' because I'm "entering the URL in the user agent's address bar"? The spec could be clarified.
Context (Chromium bug): https://bugs.chromium.org/p/chromium/issues/detail?id=859046

**Comment by rniwa** [comment]
"entering the URL in the user agent's address bar" is probably too oddly specific normative text. We probably need to say something like "the user requested the user agent to navigate to a specific URL". Then UA can determine which specific UI / UX would map to such a request.

**Comment by yoavweiss** [comment]
WG call conclusion: Navigation Timing should just point to "reload-triggered navigation".
