### ISSUE TITLE
Add a new entry type for navigations from the BFCache

### ISSUE THREAD

**Issue by philipwalton** [w3c/navigation-timing#118]
Based on discussion around #115, both at TPAC and on the [most recent call](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit?pli=1#heading=h.97v4w2low3m), I think it would make sense to have a separate navigation entry type that is dispatched when a page comes out of the BFCache.

Currently Safari will [update the values of `performance.timing`](https://github.com/w3c/navigation-timing/issues/115#issuecomment-543278278), and Firefox [will change the `navigation.type` value](https://github.com/w3c/navigation-timing/issues/115#issuecomment-533381105) on the already-dispatched entry. But both of these are problematic if code on the page has local references to the original values (which I've seen example of), so dispatching a brand new entry type seems like the safest option.

Also, since the only way to currently tell that a page is coming out of BFCache is to listen to the `pageshow` event (and inspect `event.persisted`), sites that only care about BFCache navigations in order to measure them wouldn't need to listen to an additional event handler to detect when that happens.

**Comment by npm1** [comment]
I believe the discussion from a WebPerf WG call not too long ago was to not implement this, for the time being. The decision was to attempt standardizing the timestamp they want on the pageshow event timeStamp attribute. Should we close this for now?

**Comment by philipwalton** [comment]
Yes, happy to close this, but do we have another issue to track standardizing the timestamp for the `pageshow` event?

**Comment by npm1** [comment]
Ahh yea this is why AIs from calls should have owners :) I don't think any issue has been filed, so I'll file one and then close this one.

**Comment by philipwalton** [comment]
Great, thanks!

**Comment by npm1** [comment]
Filed https://github.com/whatwg/html/issues/5226, closing.
