### ISSUE TITLE
PerformanceNavigationTiming needs a realm

### ISSUE THREAD

**Issue by npm1** [w3c/navigation-timing#125]
See https://github.com/w3c/performance-timeline/issues/162. For nav timing, the problem I see is that the object is created early in the processing model. I'm not sure if this is possible, as the object would need to specify the realm. But the document does not exist from the beginning, so I don't think we'd be able to specify that realm. To get around this problem, we can instead use vars to keep track of the values we're interested in, and create the PerformanceNavigationTiming object towards the end of the processing model, when we can now grab the final Document object and obtain the realm in which we'll be exposing this object.

**Comment by noamr** [comment]
I believe this can be closed.
