### ISSUE TITLE
3.3 Getters should not replicate processing model definitions

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#135]
In 3.3. the various getters need to be simplified so that they will not replicate the processing model logic, and instead rely on it. The underlying definition needs to rely on well-defined integration points in Fetch and/or HTML.

* [ ] unloadEventStart
* [ ] unloadEventEnd
* [ ] domInteractive
* [ ] domContentLoadedEventStart
* [ ] domContentLoadedEventEnd
* [ ] domComplete
* [ ] loadEventStart
* [ ] loadEventEnd
* [ ] redirectCount

**Comment by noamr** [comment]
I believe this can be closed.
