### ISSUE TITLE
4.1 Processing model should rely on Fetch/HTML

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#136]
* [x] "if the navigation is aborted" section is vague. It should be based on precise flags from HTML/Fetch, rather than "aborted due", "caused by", etc.
* [x] Regarding the navigation type, it'd be better to refer to a specific Document object rather than "the navigation" and tie the "history handling behavior" in HTML to the former
* [x] "if there are no redirects" is not a precise term. A precise counter from Fetch should be used instead.
* [x] "same origin check" algorithm should be provided with the previous and current document/origin as input
* The following should be tied to the Fetch/HTML processing model, instead of the current handwavy definition
  * [x] unloadEventStart 
  * [x] unloadEventEnd
  * [x] workerStart
  * [x] fetchStart
* The following should be inherited from Resource Timing (with some care around the differences between TAO and same origin checks)
  * [x] domainLookupStart 
  * [x] domainLookupEnd
  * [ ]connectStart
  * [x] connectEnd
  * [x] nextHopProtocol
  * [x] secureConnectionStart
  * [x] requestStart
  * [x] responseStart
  * [x] responseEnd
  * [x] transferSize
  * [x] encodedBodySize
  * [x] decodedBodySize
* [x] Step 20 redirect counts should be done as part of Fetch
* The following should be done as part of HTML's processing model
  * [x] domInteractive
  * [x] domContentLoadedEventStart
  * [x] domContentLoadedEventEnd
  * [x] domComplete
  * [x] loadEventStart
  * [x] loadEventEnd

**Comment by noamr** [comment]
> * [ ]  "if the navigation is aborted" section is vague. It should be based on precise flags from HTML/Fetch, rather than "aborted due", "caused by", etc.
> * [ ]  Regarding the navigation type, it'd be better to refer to a specific Document object rather than "the navigation" and tie the "history handling behavior" in HTML to the former
> * [ ]  "if there are no redirects" is not a precise term. A precise counter from Fetch should be used instead.
> * [ ]  "same origin check" algorithm should be provided with the previous and current document/origin as input
> * The following should be tied to the Fetch/HTML processing model, instead of the current handwavy definition
>   
>   * [ ]  unloadEventStart
>   * [ ]  unloadEventEnd
>   * [ ]  workerStart
>   * [ ]  fetchStart
> * The following should be inherited from Resource Timing (with some care around the differences between TAO and same origin checks)
>   
>   * [ ]  domainLookupStart
>   * [ ]  domainLookupEnd
>   * [ ]connectStart
>   * [ ]  connectEnd
>   * [ ]  nextHopProtocol
>   * [ ]  secureConnectionStart
>   * [ ]  requestStart
>   * [ ]  responseStart
>   * [ ]  responseEnd
>   * [ ]  transferSize
>   * [ ]  encodedBodySize
>   * [ ]  decodedBodySize
> * [ ]  Step 20 redirect counts should be done as part of Fetch
> * The following should be done as part of HTML's processing model
>   
>   * [ ]  domInteractive
>   * [ ]  domContentLoadedEventStart
>   * [ ]  domContentLoadedEventEnd
>   * [ ]  domComplete
>   * [ ]  loadEventStart
>   * [ ]  loadEventEnd

All of the above are handled by https://github.com/whatwg/html/pull/6536, once they're also integrated with Navigation Timing.

**Comment by noamr** [comment]
> * [x]  "if the navigation is aborted" section is vague. It should be based on precise flags from HTML/Fetch, rather than "aborted due", "caused by", etc.
> * [x]  Regarding the navigation type, it'd be better to refer to a specific Document object rather than "the navigation" and tie the "history handling behavior" in HTML to the former
> * [x]  "if there are no redirects" is not a precise term. A precise counter from Fetch should be used instead.
> * [x]  "same origin check" algorithm should be provided with the previous and current document/origin as input
> * The following should be tied to the Fetch/HTML processing model, instead of the current handwavy definition
>   
>   * [x]  unloadEventStart
>   * [x]  unloadEventEnd
>   * [ ]  workerStart
This one is still pending. See https://github.com/w3c/ServiceWorker/pull/1575

>   * [x]  fetchStart
> * The following should be inherited from Resource Timing (with some care around the differences between TAO and same origin checks)
>   
>   * [x]  domainLookupStart
>   * [x]  domainLookupEnd
>   * [ ]connectStart
>   * [x]  connectEnd
>   * [x]  nextHopProtocol
>   * [x]  secureConnectionStart
>   * [x]  requestStart
>   * [x]  responseStart
>   * [x]  responseEnd
>   * [x]  transferSize
>   * [x]  encodedBodySize
>   * [x]  decodedBodySize
> * [x]  Step 20 redirect counts should be done as part of Fetch
> * The following should be done as part of HTML's processing model
>   
>   * [x]  domInteractive
>   * [x]  domContentLoadedEventStart
>   * [x]  domContentLoadedEventEnd
>   * [x]  domComplete
>   * [x]  loadEventStart
>   * [x]  loadEventEnd

These are now resolved.
