### ISSUE TITLE
Connection time missing after redirection...

### ISSUE THREAD

**Issue by ThierryMajutec** [w3c/navigation-timing#138]
When redirecting a domain from HTTP to HTTPS (status code 301), I notice the following behavior:
- The "Redirect" time for the HTTPS connection take into account the initial connection to the domain in HTTP (DNS, CT, ...), which is good.
- When looking at the HTTPS connection though, I do not see any Connection time value (I've checked in Chrome Devtool and notice the same behavior).

Obviously, when looking in wireshark, I see two distinct TCP connections on port 80 and port 443.
Is the absence of TCP connection time as well as SSL hadnshake time in the HTTPS connection a normal behavior ?

**Comment by npm1** [comment]
> When redirecting a domain from HTTP to HTTPS (status code 301), I notice the following behavior:
> 
> * The "Redirect" time for the HTTPS connection take into account the initial connection to the domain in HTTP (DNS, CT, ...), which is good.

Yay

> * When looking at the HTTPS connection though, I do not see any Connection time value (I've checked in Chrome Devtool and notice the same behavior).
> 
> Obviously, when looking in wireshark, I see two distinct TCP connections on port 80 and port 443.
> Is the absence of TCP connection time as well as SSL hadnshake time in the HTTPS connection a normal behavior ?

Which attribute are you looking at specifically? secureConnectionStart? A sample site would be great. Also, testing the behavior in other browsers would be great (to confirm if this is indeed some spec bug or a Chrome specific bug).

**Comment by ThierryMajutec** [comment]
Hmm, it seems I cannot easily reproduce the "problem".
I've made a lot more tests and usually see the second TCP connection, with SSL time and all good stuff.
Sorry, I'll close this issue seeing I cannot reproduce.
