### ISSUE TITLE
AppCache meaning

### ISSUE THREAD

**Issue by ThierryMajutec** [w3c/navigation-timing#140]
AppCache defined in the Time Navigation API does of course correspond to the time it takes by the browser to check the cache, but not only I guess. 
Do you confirm that the waiting time in case the browser has already established 6 TCP sessions to the same hostname and waits for a slot to be available ?
Are there any other main reasons to have significant AppCache value ?

**Comment by nicjansma** [comment]
Hi @ThierryMajutec,

That's correct, the time listed as _AppCache_ in the diagram below is bound by `fetchStart` and `domainLookupStart`, and _should mostly_ represent time taken by the browser to check the local browser cache (i.e. to decide if it needs to fetch something from the network):

![NavTiming diagram](https://w3c.github.io/navigation-timing/timestamp-diagram.svg)

The [`fetchStart`](https://w3c.github.io/navigation-timing/#dom-performancetiming-fetchstart) attribute definition mentions this:

* `fetchStart must return the time immediately before the user agent starts checking any relevant application caches.`

> Do you confirm that the waiting time in case the browser has already established 6 TCP sessions to the same hostname and waits for a slot to be available ?

I think most of the ["blocking time"](https://nicj.net/resourcetiming-in-practice/#blocking-time) (when waiting for an already-established connection to be free) will be between `connectEnd` and `requestStart` instead.

> Are there any other main reasons to have significant AppCache value ?

Not that I'm aware, but each browser is free to do whatever work it thinks is necessary during the fetch timeline.   At mPulse (a RUM provider) we have generally assumed time between `fetchStart` and `domainLookupStart` was _mostly_ cache lookup time (i.e. time it takes to spin up the disk and check if content exists/is usable or not).

I was curious to see how frequently we see time spent during the _AppCache_ block above.  I looked at our mPulse RUM data, and over a few billion page loads, I see:

* 28% of page loads have at least 1ms difference between `fetchStart` and `domainLookupStart`
* 50th percentile App Cache duration is 8ms
* 75th percentile App Cache duration is 29ms
* 95th percentile App Cache duration is 253ms

If we look at just App Cache durations from 0ms to 1,000ms, we see a lognormal distribution of times:

<img width="816" alt="app-cache-zoom" src="https://user-images.githubusercontent.com/1004649/114445763-741b0d00-9b9e-11eb-8e96-153610a465cb.png">

The last bucket at 1,000ms in the first graph represents all data taking at least 1,000ms or higher.

The second chart zooms into the durations from 1,000ms to 60,000ms (i.e. the final bucket in the first picture).  There's a an interesting spike at 10,000ms (10s) and another small one at 20,000ms (20s).  My guess is some browsers have cache-lookup timeouts at 10s/20s, and go to network instead?

Anyways, I'd be curious if any browser developers know differently, or if there's other common work done between those two timestamps.

By the way, though it's called **AppCache** in the diagram above, I don't believe this is supposed to be a reference to the [AppCache](https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache) browser feature that is being removed.  It's meant to just be the "App Cache" lookup time.

**Comment by noamr** [comment]
Can this be closed? I think this is clear both in the diagram and in the FETCH spec.

**Comment by yoavweiss** [comment]
Should we rename "AppCache" in the diagram to simply "Cache"?

**Comment by noamr** [comment]
> Should we rename "AppCache" in the diagram to simply "Cache"?

 I believe so. I don't have access to the diagrams though, @nicjansma ?

**Comment by yoavweiss** [comment]
It's in https://github.com/w3c/navigation-timing/blob/gh-pages/timestamp-diagram.svg

**Comment by noamr** [comment]
> It's in https://github.com/w3c/navigation-timing/blob/gh-pages/timestamp-diagram.svg

Yea that's generated from somewhere and not editable.

**Comment by yoavweiss** [comment]
It seems like at least one [past commit](https://github.com/w3c/navigation-timing/commit/b59240c730c7c51667a689b704b4157ec3de1983) changed it directly. 
@nicjansma - do you know more about this?

**Comment by noamr** [comment]
> It seems like at least one [past commit](https://github.com/w3c/navigation-timing/commit/b59240c730c7c51667a689b704b4157ec3de1983) changed it directly. @nicjansma - do you know more about this?

It was committed directly but probably authored elsewhere and re-exported. It looks like a Google Doc diagram.
