### ISSUE TITLE
Spec needs a serious rewrite 

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/navigation-timing#147]
This spec needs a serious rewrite. In particular, it should:

 * drop all instances of `data-cite=`
 * Fixup it ReSpec / xref usage per the docs
 * drop the "obsolete" section
 * stop monkey patching underlying specs - those specs should be updated instead.

**Comment by yoavweiss** [comment]
> * drop all instances of `data-cite=`

Agree that this would be great.

> * Fixup it ReSpec / xref usage per the docs

Any specific pointers/issues?


> * drop the "obsolete" section

I don't think we want to do that. The section defines an API that's still shipped in browsers and we're unlikely to unship anytime soon.


> * stop monkey patching underlying specs - those specs should be updated instead.

Any specific pointers to where we do that? I believe we fixed a lot of vagueness as part of the [HTML integration](https://github.com/w3c/navigation-timing/pull/141)

**Comment by marcoscaceres** [comment]
> Any specific pointers/issues?

Basically the ones I raised in: 
https://github.com/w3c/navigation-timing/pull/143/

Where we had to stop trying to link to things for now... anyway, @caribouW3 and I are going to start working on those this week. Expect a few PRs... I'm hoping we can chip away at them incrementally across all the Web Perf specs and make the all super nice and easier to maintain 💅. 

> Any specific pointers to where we do that? I believe we fixed a lot of vagueness as part of the HTML integration

I was this kind of thing, which is now fixed as part of #143: 
https://github.com/w3c/navigation-timing/pull/143/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R312

**Comment by marcoscaceres** [comment]
Closing this issue as it's not specific enough.

**Comment by marcoscaceres** [comment]
Just FYI for folks following along - we have a nice ReSpec shorthands guide:

https://respec.org/docs/#Shorthands-Guide

Plus all the docs have been updated with more examples, screenshots, and structured for quick search/copy paste.

**Comment by yoavweiss** [comment]
> I'm hoping we can chip away at them incrementally across all the Web Perf specs and make the all super nice and easier to maintain 💅.

That'd be awesome and highly appreciated!! :)
