### ISSUE TITLE
Add a test that ensures `fetchStart` matches the SW's fetch event start time

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#148]
Followup on #143.
We should extend [NavigationTiming's SW test](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/external/wpt/service-workers/service-worker/navigation-timing.https.html?q=workerStart%20f:wpt&ss=chromium) to cover matching times.

**Comment by noamr** [comment]
Done
