### ISSUE TITLE
window.performance.timing mention

### ISSUE THREAD

**Issue by plehegar** [w3c/navigation-timing#15]
[[
Small edit, the spec does make one reference to 
window.performance.timing in Step 20.f of the Processing Model, which 
should probably be updated.
]]
https://lists.w3.org/Archives/Public/public-web-perf/2015Jun/0056.html

**Comment by toddreifsteck** [comment]
@plehegar We have accepted both merges but I did not close the issue as I wanted your final review before doing so. Could you close if this is considered complete?

**Comment by igrigorik** [comment]
I believe all the pieces are in place, closing. @plehegar please reopen if otherwise.
