### ISSUE TITLE
 The unloadEventEnd attribute

### ISSUE THREAD

**Issue by yujun-0127** [w3c/navigation-timing#151]
this description is incorrect, it's same with `unloadEventStart`

![图片](https://user-images.githubusercontent.com/9698838/124448987-96937f80-ddb5-11eb-8597-cad8a5d7b1b1.png)

**Comment by nicjansma** [comment]
Hi @yujun-0127 -- I think in the current [Editor's Draft](https://w3c.github.io/navigation-timing/), this should be properly specified:

https://w3c.github.io/navigation-timing/#dom-performancetiming-unloadeventend

> If the previous document and the current document have the same same origin, this attribute must return the time immediately *after* the user agent finishes the unload event of the previous document

and

> The unloadEventEnd getter steps are to return this's previous document unload timing's unload *event end time*.

Please review and let us know

**Comment by aramyesildeniz** [comment]
MDN defines also with "after finishes unload event":

_The unloadEventEnd read-only property returns a timestamp representing the time value equal to the time immediately after the user agent finishes the unload event of the previous document. If there is no previous document, this property value is 0._

cf. https://developer.mozilla.org/en-US/docs/Web/API/PerformanceNavigationTiming/unloadEventEnd

**Comment by nicjansma** [comment]
Closing as the latest draft and Level 2 docs have the correct description, please let us know if you've found the wrong definition published elsewhere
