### ISSUE TITLE
Should about:blank have a PerformanceNavigationTiming?

### ISSUE THREAD

**Issue by achristensen07** [w3c/navigation-timing#155]
I found that Firefox does but Chrome and now WebKit do not.  https://www.w3.org/TR/navigation-timing-2/#marking-navigation-timing isn't clear to me about what to do in this case.  I added a test in https://github.com/web-platform-tests/wpt/pull/30295

**Comment by npm1** [comment]
@yoavweiss do you know?

**Comment by yoavweiss** [comment]
[Creating an NT entry](https://www.w3.org/TR/navigation-timing-2/#dfn-create-the-navigation-timing-entry) is called from step 16 of [Initialize the Document object](https://html.spec.whatwg.org/multipage/browsing-the-web.html#initialise-the-document-object). I *think* that means that it's supposed to be called for about:blank pages, but asked for clarifications, as the processing model there is not 100% clear to me.

**Comment by noamr** [comment]
By the spec amendment, `about:blank` should *not* have a navigation timing entry, as it's not called from [create and initialize the document](https://html.spec.whatwg.org/#initialise-the-document-object), and doesn't have a FETCH response. Resource/navigation timing entries are almost always mapped to some FETCH response.

**Comment by noamr** [comment]
I believe it's ok to submit that test, and it would be marked as failed for Firefox.

**Comment by noamr** [comment]
Specifically, IIUC `about:blank`'s document is created [here](https://html.spec.whatwg.org/multipage/browsers.html#creating-browsing-contexts:is-initial-about:blank), without `navigation params` and everything that goes into initializing a document.

**Comment by yoavweiss** [comment]
Thanks for investigating! /cc @bdekoz

**Comment by noamr** [comment]
Closing. Feel free to reopen if something is still unclear.
