### ISSUE TITLE
ToT spec has a bunch of respec warnings and errors

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#167]
I'm seeing warnings RE editors emails, spurious definitions, but also trying it locally, I see errors around session history dfns no longer being exported from HTML. I'm not sure if this is a recent change.

/cc @noamr

**Comment by noamr** [comment]
> I'm seeing warnings RE editors emails, spurious definitions, but also trying it locally, I see errors around session history dfns no longer being exported from HTML. I'm not sure if this is a recent change.
> 
> 
> 
> /cc @noamr 

On it.
