### ISSUE TITLE
performance.timeOrigin vs performance.timing.navigationStart

### ISSUE THREAD

**Issue by Quadiago** [w3c/navigation-timing#183]
Hi all!

I've been bashing my head at a problem we've started seeing in Chrome 105 and 106 that leads me to the simple question:

**What is `timeOrigin` compared to `navigationStart`?** 

[Every definition](https://www.w3.org/TR/hr-time-3/#dfn-get-time-origin-timestamp) [and](https://github.com/w3c/navigation-timing/issues/160) [comment](https://github.com/whatwg/html/issues/7716) I can find suggests that they are supposed to be the same, but our data (collected through RUM) suggests differently. Manual testing in Chrome also always shows a difference (which is confirmed by [this](https://wpt.live/hr-time/timeOrigin.html)):

![image](https://user-images.githubusercontent.com/55053485/198033751-d600a44b-7581-4224-86db-0c66a77ade91.png)

Any advice would be appreciated.

**Comment by Quadiago** [comment]
Thanks for responding @yoavweiss . But do you mind confirming, at least according to spec, that timeOrigin is supposed to match  navigationStart?

**Comment by yoavweiss** [comment]
It is supposed to match it. See note under https://www.w3.org/TR/navigation-timing-2/#dom-performancetiming-navigationstart
