### ISSUE TITLE
PerformanceNavigation.TYPE_RESERVED should be 255 (or be removed)

### ISSUE THREAD

**Issue by foolip** [w3c/navigation-timing#28]
So says http://www.w3.org/TR/navigation-timing/#sec-navigation-info-interface

It's really weird, but changing it does not seem useful. The constant is never actually used in Blink, so if any change here is worthwhile, it would be to remove TYPE_RESERVED entirely.

Follow-up to https://github.com/w3c/navigation-timing/issues/22

**Comment by plehegar** [comment]
http://w3c-test.org/navigation-timing/test_navigation_type_enums.html
and
http://w3c-test.org/navigation-timing/idlharness.html
indicates that the constant exists and is 255.

**Comment by plehegar** [comment]
(if this gets accepted, I'll issue an errata as well)

**Comment by foolip** [comment]
Errata? Is there a spec where it was 3 other than the one now being fixed?

**Comment by plehegar** [comment]
oh right, I mixed stuff up (again). No errata needed. The error was introduced by me.

**Comment by igrigorik** [comment]
Closed via #30.
