### ISSUE TITLE
PerformanceTiming#dom* attributes are poorly defined

### ISSUE THREAD

**Issue by igrigorik** [w3c/navigation-timing#35]
Source: https://lists.w3.org/Archives/Public/public-web-perf/2015Aug/0013.html

> 
> > domLoading attribute
> > 
> > This attribute must return the time immediately before the user
> > agent sets the current document readiness to "loading".
> 
> or in the Processing Model:
> 
> > Record the time as domLoading immediately before the user agent
> > sets the current document readiness to "loading".
>
> The "current document readiness" of what? I'm willing to accept that a
> PerformanceTiming object has an implicit reference to the Window
> through the Performance object from which it was retrieved (though
> that should be clarified too), but even if there is a 1-to-1 mapping
> from the Window object to the Document object in general, there are
> exceptions.

**Comment by igrigorik** [comment]
First, domLoading is deprecated: https://lists.w3.org/Archives/Public/public-web-perf/2015May/0030.html

That said, looking at another metric, like [domComplete](http://w3c.github.io/navigation-timing/#widl-PerformanceNavigationTiming-domComplete): 

> This attribute must return a DOMHighResTimeStamp with a time value equal to the time immediately before the user agent sets the [current document readiness](http://www.w3.org/TR/html5/dom.html#current-document-readiness) to "complete" [HTML5].

It sounds like the point of confusion is "document"? What are the exceptions here? Need more feedback.

**Comment by Ms2ger** [comment]
Right, as I said, you're not defining which document you're talking about.

**Comment by plehegar** [comment]
In the case of Navigation Timing, the "current document"  is the one represented by "the Window object's newest Document object."

**Comment by plehegar** [comment]
See https://github.com/w3c/navigation-timing/pull/36

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/navigation-timing/pull/36, closing.

**Comment by plehegar** [comment]
https://github.com/w3c/hr-time/pull/14#issuecomment-144123008
