### ISSUE TITLE
Contribute tests for navigation timing

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-timing#39]

**Comment by igrigorik** [comment]
@toddreifsteck @plehegar any progress on this?

**Comment by toddreifsteck** [comment]
Sent a zip of the improved testing over to @plehegar last week. He reported in email that he has had good luck getting them to run on multiple browsers.

**Comment by igrigorik** [comment]
*bump*.. @plehegar @toddreifsteck any updates on this one?

**Comment by igrigorik** [comment]
Tests landed in https://github.com/w3c/web-platform-tests/pull/4262, closing. For new/missing tests, let's use https://github.com/w3c/navigation-timing/issues/58.
