### ISSUE TITLE
It is not defined what "The PerformanceNavigationTiming interface participates in the [PERFORMANCE-TIMELINE-2] " means

### ISSUE THREAD

**Issue by smaug----** [w3c/navigation-timing#46]
How does an interface "participate" something else?
Does it just mean that some  PerformanceEntry objects are queued? If so, when?

**Comment by smaug----** [comment]
Oh, maybe I can understand this now... It is queued

**Comment by plehegar** [comment]
indeed, it's queued in step 27 of the processing model. "participates" means it gets exposed through the performance timeline (getEntries*, perf observers). Performance timeline never mentions what participation means. I could certainly add something in perf timeline and then link the word participate to it if you think it would help.

**Comment by smaug----** [comment]
yes, that would help and "extends the following attributes of the PerformanceEntry interface." is also very weirdly said, since nothing is extended there.

**Comment by igrigorik** [comment]
@plehegar do we really need to? Now that we have a hook to queue the entries for delivery via PerformanObserver, I think it's implicit. I think we could just drop the "participates" stuff altogether to keep thing simple?

**Comment by igrigorik** [comment]
I believe this is a near duplicate of https://github.com/w3c/resource-timing/issues/55?

**Comment by igrigorik** [comment]
Dropped "participates" language in https://github.com/w3c/navigation-timing/commit/a2b8521da0989e09d2ba06dc6eaa87fdd13975fa. As noted earlier, steps 27 & 28 ("add" and "queue") already provide the necessary hooks.

**Comment by plehegar** [comment]
one comment on this one: should we use "affects the following attributes" instead of "extends the following attributes"?

**Comment by igrigorik** [comment]
*shrug*.. not sure on this one. FWIW, we use "extends" in other specs. If there is a strong argument for "affects" I'm happy to change those -- let me know.

**Comment by plehegar** [comment]
If you're not sure, then let's keep the text as-is.
