### ISSUE TITLE
enum values should be hyphenated

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/navigation-timing#47]
`NavigationType` uses 'back_forward' as an enum value; the [convention for enum values](https://w3ctag.github.io/design-principles/#casing-rules) is to used hyphenated names

**Comment by plehegar** [comment]
may not be too late to change that. @toddreifsteck ?

**Comment by foolip** [comment]
Has any engine begun implementing this yet? There's currently an [Intent to Implement and Ship](https://groups.google.com/a/chromium.org/d/msg/blink-dev/AT7aqhPcNdw/10jQ2B0HAQAJ) on blink-dev and it'd be nice to resolve this.

**Comment by toddreifsteck** [comment]
IE11 will not be changing and implemented NavigationType years ago. Microsoft Edge 12 has had this enum since shipping with it in July 2015. Although the spec does not properly follow convention, I think it would be best to stick with what the active implementations have in the wild. @igrigorik ?

**Comment by igrigorik** [comment]
I agree with @toddreifsteck. We should have caught this much earlier. We can put an html comment in the spec marking it as a known issue.. as a warning to future updates. Does that sound reasonable?

**Comment by dontcallmedom** [comment]
I'm not sure what you mean by an HTML comment - but if you mean `<!-- -->`, I think it would be better to have a visible note in the spec with an explanation, if only to avoid others re-raising this issue.

(but otherwise, sounds like a good reason to keep it as is indeed)

**Comment by toddreifsteck** [comment]
We will add a visible note to the spec stating it is being kept in the nonconventional enum format to ensure the feature continues to work as expected in long-shipped implementations.

**Comment by foolip** [comment]
That answers my question, thanks, I had no idea this had shipped, and so long ago too. A note saying "oops" sounds good.

**Comment by igrigorik** [comment]
@foolip @dontcallmedom do we have a link that I can point to, that explains the convention?

**Comment by foolip** [comment]
https://heycam.github.io/webidl/#idl-enums says "It is strongly suggested that enumeration values be all lowercase, and that multiple words be separated using dashes or not be separated at all, unless there is a specific reason to use another value naming scheme."

**Comment by igrigorik** [comment]
@foolip thanks! Pushed an update.. hope that looks good / let me know if otherwise.

**Comment by foolip** [comment]
LGTM!
