### ISSUE TITLE
Processing Model is confusing in respect of startTime and beforeunload

### ISSUE THREAD

**Issue by ahest** [w3c/navigation-timing#48]
The Processing Model diagram shows only a subset of possible situations, i.e. the case with beforeunload dialog present (in the case where beforeunload handler was run but there was no confirmation dialog, startTime should mark the point before the "Prompt for unload" square).
It must be made clear to the readers, or (probably better) the diagram should be changed to show two possible situations.

Also the steps described in Processing Model do not specify at which point "prompting to unload" the previous document happens.

(see the discussion in https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!topic/loading-dev/W5MbNq5ScLs)

**Comment by igrigorik** [comment]
Re, diagram: https://github.com/w3c/navigation-timing/issues/44#issuecomment-261399994 should address this.

> Also the steps described in Processing Model do not specify at which point "prompting to unload" the previous document happens.

Right, and I believe it's out of scope for NT. As in, we have hooks in steps  [steps 7 and 8](http://w3c.github.io/navigation-timing/#process) to record the timestamps of when the unload prompt is triggered, but I don't think it's our job to define when/why that might be the case -- that's the job of the HTML spec. Is that reasonable?

**Comment by igrigorik** [comment]
Closing, I believe we addressed this via https://github.com/w3c/navigation-timing/issues/44#issuecomment-261399994. Please feel free to reopen if otherwise.
