### ISSUE TITLE
Transition Level 2 to CR

### ISSUE THREAD

**Issue by igrigorik** [w3c/navigation-timing#49]
- **Known / outstanding spec issues**
  - [ ] https://github.com/w3c/navigation-timing/milestone/1
- **Web platform tests**
  - [x] https://github.com/w3c/navigation-timing/issues/39
  - [x] https://github.com/w3c/web-platform-tests/pull/4262
- **Privacy and security**
  - [x] http://w3c.github.io/navigation-timing/#privacy
  - [x] http://w3c.github.io/navigation-timing/#security
- **Implementations**
  - [x] Edge: [Edge build 10240+](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/navigationtimingapi/); [partial support](https://developer.microsoft.com/en-us/microsoft-edge/platform/catalog/?q=specName%3Anavigation-timing-2)
  - [x] Chrome: [M57](https://www.chromestatus.com/feature/5409443269312512)
  - [ ] Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1043083
  - [ ] Safari: no public signals
- [x] Update acknowledgement section

**Comment by yoavweiss** [comment]
In our [charter](https://www.w3.org/2021/02/webperf.html) discussions we decided to move to a Living Standard model, so this is no longer relevant. Closing
