### ISSUE TITLE
Automatic publication of the spec fails due to markup errors

### ISSUE THREAD

**Issue by tripu** [w3c/navigation-timing#57]
Last successful publication of `navigation-timing` with Echidna was [on 22 Apr](https://www.w3.org/TR/2016/WD-navigation-timing-2-20160422/); after that, [all jobs submitted have failed](https://www.w3.org/Search/Mail/Public/search?keywords=&hdr-1-name=subject&hdr-1-query=navigation-timing&index-grp=Public_FULL&index-type=t&type-index=public-tr-notifications).

One step that is erroring is HTML validation. In particular:

* &ldquo;Element `div` not allowed as child of element `ul` in this context&rdquo;
* &ldquo;Element `div` not allowed as child of element `dl` in this context&rdquo;
* &ldquo;Bad value `100%` for attribute `width` on element `img`: expected a digit but saw `%` instead&rdquo;

And also one Echidna-specific check:

* &ldquo;No valid HTTPS link to public list of disclosures (`https://www.w3.org/2004/01/pp-impl/NNNNN/status`)&rdquo;

eg, [`labs.w3.org/echidna/api/status?id=019c95fb-4fa1-4f5d-98e4-c03610c8b4e0`](https://labs.w3.org/echidna/api/status?id=019c95fb-4fa1-4f5d-98e4-c03610c8b4e0)

--

(Assigning all contributors who have committed since the last successful publication, and pinging @marcoscaceres. Let me know if you need help!)

**Comment by igrigorik** [comment]
@tripu any tips for how I can validate / run these checks locally?

**Comment by tripu** [comment]
@igrigorik, [your Echidna manifest](https://github.com/w3c/navigation-timing/blob/gh-pages/W3CTRMANIFEST) says the spec should be generated by ReSpec.

You can use [our online instance of spec-generator](https://labs.w3.org/spec-generator/) to process the source document with ReSpec

[`https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/navigation-timing/?specStatus=WD;shortName=navigation-timing-2`](https://labs.w3.org/spec-generator/?type=respec&url=https://w3c.github.io/navigation-timing/?specStatus=WD;shortName=navigation-timing-2)

and submit that URL to [Pubrules](https://www.w3.org/pubrules/)

[`https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fnavigation-timing%2F%3FspecStatus%3DWD%3BshortName%3Dnavigation-timing-2&profile=WD`](https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttps%3A%2F%2Fw3c.github.io%2Fnavigation-timing%2F%3FspecStatus%3DWD%3BshortName%3Dnavigation-timing-2&profile=WD)

**Comment by siusin** [comment]
@igrigorik this URL can generate a virtual working draft from the ED and validate it on  the pubrule checker:
https://www.w3.org/pubrules/?url=https%3A%2F%2Flabs.w3.org%2Fspec-generator%2F%3Ftype%3Drespec%26url%3Dhttp%3A%2F%2Fw3c.github.io%2Fnavigation-timing%2Findex.html%3FspecStatus%3DWD%3BshortName%3Dnavigation-timing&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004

To fix the link to disclosures issues, please try use https on L97 wgPatentURI.

**Comment by plehegar** [comment]
Also fixed in c76d96cd102d408e86f8f8abce329a566adcb3fc

**Comment by plehegar** [comment]
Success!  https://lists.w3.org/Archives/Public/public-tr-notifications/2016Dec/0052.html
