### ISSUE TITLE
Effect of canceled navigation on navigation timing

### ISSUE THREAD

**Issue by bripkens** [w3c/navigation-timing#60]
It seems like the abort conditions (under processing model) are missing a bullet point on user initiated canceled page loads. Specifically, what happens when the user cancels page loads.

I quickly tried this in Chrome and Safari (both latest stable), they will both cancel gathering of navigation timing data and will list the remaining data points with their initial value.

**Comment by igrigorik** [comment]
Good point, we should probably add ~"The user aborts the navigation" bullet point under [step 1](http://w3c.github.io/navigation-timing/#processing-model).

> I quickly tried this in Chrome and Safari (both latest stable), they will both cancel gathering of navigation timing data and will list the remaining data points with their initial value.

The behavior is—I believe—as expected.. correct? As in, if the navigation is aborted before the value is initialized then it should report its initial value.

**Comment by bripkens** [comment]
> The behavior is—I believe—as expected.. correct? As in, if the navigation is aborted before the value is initialized then it should report its initial value.

I'd say so, yes. It would be consistent to the other abort clauses.
