### ISSUE TITLE
IDL should xref PerformanceResourceTiming

### ISSUE THREAD

**Issue by annevk** [w3c/navigation-timing#64]
Please consider using https://github.com/tabatkins/bikeshed which handles this and much more automatically.

**Comment by toddreifsteck** [comment]
We should ensure that this is cross-linked even if we don't move to bikeshed.

**Comment by igrigorik** [comment]
Updates in https://github.com/w3c/navigation-timing/commit/6ebf3b247a3452ceb3f3ceefcf31df076129987d resolved this. Both mentions of `PerformanceResourceTiming` (including IDL) are linked to RT spec.
