### ISSUE TITLE
Please fix at least your broken links, if you want anyone to ever make any sense of your specs

### ISSUE THREAD

**Issue by bzbarsky** [w3c/navigation-timing#65]
Start at either https://www.w3.org/TR/navigation-timing-2/#sec-PerformanceNavigationTiming or https://w3c.github.io/navigation-timing/#sec-PerformanceNavigationTiming and try to walk the ancestor interface chain for the PerformanceNavigationTiming interface.

What, you say "PerformanceResourceTiming" is not linkified in the IDL?  Why would an implementor ever need to know silly things like what this interface actually inherits from?

OK, search around in the document, find section 4.2 which has a link to <https://www.w3.org/TR/resource-timing/#idl-def-PerformanceResourceTiming>.  Oops, that's a broken link: no such anchor.

OK, search in the document, find https://www.w3.org/TR/resource-timing/#performanceresourcetiming which says it inherits from PerformanceEntry.  Which is of course not linkified.  Search in the document some more, find two prose bits that link to PerformanceEntry.  Both those links point to https://www.w3.org/TR/hr-time-2/#dom-performanceentry which is awesome because that document doesn't even mention PerformanceEntry.  Same thing for the editors' drafts of both resource-timing and hr-time, by the way.  The editor's draft of resource-timing at https://w3c.github.io/resource-timing/ instead links to https://www.w3.org/TR/performance-timeline-2/#performanceentry which is _also_ a broken link: no such anchor.  At least it's the right document, finally, in the sense of defining a PerformanceEntry interface.  Whether it defines the PerformanceEntry interface that the editor's draft of navigation-timing expects, or whether that's https://w3c.github.io/performance-timeline/, I dunno.

So here's my question: how is anyone ever expected to implement this pile of broken links?

N.B.: I haven't even found the part I was looking for, which is the action at a distance about PerformanceEntry instances having magic happen about adding them to the performance entry buffer when they get constructed.  Presumably that's defined in some yet other spec which is carefully not linked from  anywhere that anyone might be able to find it.

**Comment by tripu** [comment]
@bzbarsky, I'll let the editors of those specs answer in detail (I suggest [`w3c/link-checker`](https://github.com/w3c/link-checker), deployed at [`validator.w3.org/checklink`](https://validator.w3.org/checklink), to check links).

About the publication process in general: it was decided that specs that go through the automatic publication system (aka Echidna) are not checked for broken links, for several reasons. Still, we think we could implement an *optional* link-checking feature (https://github.com/w3c/echidna/issues/426) to assist editors with this.

**Comment by bzbarsky** [comment]
To be clear, this situation is due partly due to a silly publication/authoring process (why exactly is the parent interface in the IDL not linkified?  It absolutely should be), but largely due to a systematic problem in the way the web performance working group develops its specifications.

**Comment by toddreifsteck** [comment]
@bzbarsky makes a good point that our specs are quite broken while we have broken links. This seems like an effort worth driving on all specs to ensure the specs are usable. @igrigorik , lets discuss how to distribute this work on 7/26 call. I suspect each spec only takes a few hours of review to enhance.

Also.. I'm interested in the systematic problem Boris describes. Boris, could you describe the problem in more detail and your proposed solution?

**Comment by bzbarsky** [comment]
There are two systematic problems,

The first problem is that the working group has specs which are strongly coupled and need to be published in sync (or be a single spec, really) but everyone pretends that they're weakly coupled and can be published independently.  This leads to contradictions between the spec drafts, things falling through cracks and not being specified because multiple specs all assume someone else is defining them, weird nonlocal behavior where algorithm specs defined by spec A actually imply that some steps from spec B happen in the middle somewhere but never actually say so, etc.

All of this makes the specs very hard to approach for implementors; I have yet to do a code review for code implementing any of this stuff where I had more than 30% confidence that the code actually agreed with the spec (insofar as this is even possible) at the end of the process.  At no point did I find it possible to do such an implementation without asking for clarifications in issues or on the mailing list.  The mail at https://lists.w3.org/Archives/Public/public-web-perf/2017Apr/0006.html agrees with this, by the way, even though it's trying to make it sound like it's perfectly OK for a spec to not be implementable without personal conversation with the spec editors.  It's not OK; it's a sign of a bad spec.

My proposed solution here is to drop the pretense of small cleanly decoupled specs when the reality is that the working group doesn't have that.  I realize that there are some W3C process issues involved, and particular W3C staff that are invested in the current setup and so forth, which make implementing this solution nontrivial.

The second systematic problem is that none of what I wrote above is new; I have written it multiple times over the last several years.  Every time this comes up the working group acts all shocked and surprised that I think there's a problem and ask me to re-explain it yet again, and doesn't listen and then we repeat.  This is why I gave up on this working group; see <https://lists.w3.org/Archives/Public/public-web-perf/2017Apr/0000.html>.  I'm sort of sorry I'm wasting more time on this yet again...  I really should stop trying.

**Comment by toddreifsteck** [comment]
Thanks for explaining and for your time, Boris. I know your time is valuable and have been in your shoes of being frustrated when being listened to..... Sometimes it takes a few attempts for communicated ideas to be fully understood. I'm sorry if I, personally, did not fully absorb and understand your communications previously.

I believe you are primarily referring to the following hierarchy of specifications.
HR-Time
-Performance Timeline
--Resource Timing
---Navigation Timing
--User Timing
--Server Timing
--Frame Timing
--Long Tasks

Other specifications in the group's repos (in various states):
Page Visibility
Beacon
Preload
Resource Hints
Cooperative Scheduling
Network Error Logging
Reporting
setImmediate

There are 3 things that should be made true for all specs:
1. All references to OTHER specifications should ensure that all content within a spec is linked to the relevant spec or subsection of the current spec
2. The target content in another spec MUST be cleaned up or we should consider the spec referencing that spec "unable to be understood"
3. If there is tight coupling between specs, we should consider combining those specs or "upstreaming" to avoid unnecessary duplication and confusion..

Is that an accurate assessment of what you are saying?

**Comment by bzbarsky** [comment]
> I believe you are primarily referring to the following hierarchy of specifications.

Yes, that's correct.

> There are 3 things that should be made true for all specs:

That seems like a reasonable summary, yes.

**Comment by toddreifsteck** [comment]
Ensuring all links are working is critical before publishing L2. Ensuring links are ensured to work regularly is a separate issue that the working group will tackle. We are using this issue to track the L2 requirement.

**Comment by marcoscaceres** [comment]
We discussed this internally at Mozilla and we would again like to encourage the group to merge the timing specs. 

Doing so would solve a lot of issues and allow Mozilla folks to more actively participate in this WG. Current setup is not ideal for us and I'm told it is leading to interop issues across UAs. 

We have folks at Mozilla that are keen to participate and that are supportive of the work. Can we work to a solution here?

**Comment by igrigorik** [comment]
Thanks for the feedback Marcos. I think this is a discussion we should have as a group on our next WG call (scheduled for [Jan 5th @ 10AM PST](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit#heading=h.r14xofqt4ph1)). Can you and/or other Mozilla folks join at that time to work through the proposal and motivation?

In the meantime, a couple quick questions (we can defer them to the call):
- Which specific specs do you guys have in mind? 
- Any particular examples of interop issues that were brought up due to existing structure?
- I'd, of course, love to see and encourage more participation.. Could you elaborate more on which topics, who, and what we can do to help encourage that?

I'd also love to hear from @siusin and @plehegar for their perspective on potential implications in terms of W3C process and publishing.

_p.s. happy holidays everyone! :-)_

**Comment by plehegar** [comment]
imho, that should be feasible and, unless we were about to reach Proposed Recommendation for one of the timelines, we can potentially minimize the impact.

**Comment by igrigorik** [comment]
Note: we discussed this on 1/5/18 WG call but unfortunately we did not have anyone from Mozilla on the call to present full context of https://github.com/w3c/navigation-timing/issues/65#issuecomment-352963176. The ask from the group is to have someone from Mozilla to join one of the upcoming calls to work through how we can best address the raised points.

Next call is [Jan 18 @ 11AM PST](https://docs.google.com/document/d/10dz_7QM5XCNsGeI63R864lF9gFqlqQD37B4q8Q46LMM/edit#heading=h.h41y1bcd3us8).

**Comment by bzbarsky** [comment]
For the obvious people at Mozilla who might be able to do it, that corresponds to 6am and 8pm, neither of which is within work hours.  This is why sync calls are a bad way to do business.

**Comment by igrigorik** [comment]
@bzbarsky who are the right folks and what are their timezones? We can shift times of one of the upcoming meetings to accommodate. Even better if we can find a time that works for everyone as an ongoing commitment.

**Comment by bzbarsky** [comment]
I'll let Marcos speak for himself if he wants to say what his timezone is.  I'd need to do some work to confirm whether the people in Europe I'm thinking of are in fact available/interested, but that would the the "8pm" timezone.

**Comment by yoavweiss** [comment]
Going back to this issue, it seems like this can be divided into two pieces:

* NavTiming and ResourceTiming should be merged - this is something we discussed and agree would be a valuable long-term effort (even if costly). That work is tracked at https://github.com/w3c/navigation-timing/issues/78
* Broken links should actually be fixed - That's the piece that seems most urgent.

Is that a correct summary of this thread?

**Comment by igrigorik** [comment]
I believe so. The meta point about links is getting process+infrastructure in place to ensure that bad links are detected before they become a problem.

**Comment by bzbarsky** [comment]
> Is that a correct summary of this thread?

Yes, though the set of specs to merge might be larger; I haven't checked which pieces live where nowadays.

The goal should be no comefrom or hidden behavior in spec algorithms, imo.

**Comment by yoavweiss** [comment]
Closed by #91, #94 and #95.

Filed https://github.com/w3c/web-performance/issues/26 to keep track of the higher level issue.

Closing
