### ISSUE TITLE
Obsolete partial interface to the Performance has incorrect exposure setting

### ISSUE THREAD

**Issue by SaschaNaz** [w3c/navigation-timing#70]
http://www.w3.org/TR/2017/WD-navigation-timing-2-20170509/#extensions-to-the-performance-interface

```webidl
partial interface Performance {
    [SameObject]
    readonly attribute PerformanceTiming     timing;
    [SameObject]
    readonly attribute PerformanceNavigation navigation;
};
```

The partial interface need a new `[Exposed=Window]` attribute, as original Performance interface has `[Exposed=(Window,Worker)]` and both the PerformanceTiming and PerformanceNavigation are only exposed to Window.

**Comment by igrigorik** [comment]
Note that you're linking to the obsolete (Nav Timing 1) interface. 
- https://www.w3.org/TR/2017/WD-navigation-timing-2-20170509/#dom-performancenavigation - exposed on Window
- https://www.w3.org/TR/2017/WD-navigation-timing-2-20170509/#dom-performancetiming - exposed on Window

My understanding is that we don't need another [Exposed] on the partial? @plehegar sanity check?

**Comment by plehegar** [comment]
correct:
[[
The exposure set of the partial interface or namespace is the exposure set of the original interface or namespace definition.
]]
https://heycam.github.io/webidl/#Exposed

**Comment by plehegar** [comment]
However, while the interfaces of PerformanceTiming and PerformanceNavigation are only exposed to Window, the Performance interfaces is exposed to Window and Workers, so the attributes timing and navigation would inherit that extended attribute. I think it does make sense to change it:
[[
partial interface Performance {
    [Exposed=(Window),SameObject]
    readonly attribute PerformanceTiming     timing;
    [Exposed=(Window),SameObject]
    readonly attribute PerformanceNavigation navigation;
};
]]

**Comment by SaschaNaz** [comment]
I suggest:

```WebIDL
[Exposed=Window]
partial interface Performance {
    [SameObject]
    readonly attribute PerformanceTiming     timing;
    [SameObject]
    readonly attribute PerformanceNavigation navigation;
};
```

**Comment by igrigorik** [comment]
That seems reasonable. @plehegar any objections?

**Comment by toddreifsteck** [comment]
@plehegar , could you take a look? Simple WebIDL review.

**Comment by plehegar** [comment]
sounds good to me

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/navigation-timing/pull/76.
