### ISSUE TITLE
WebIDL serializer has been deprecated in favor of toJSON operation

### ISSUE THREAD

**Issue by tobie** [w3c/navigation-timing#72]
Hi!

We recently [deprecated WebIDL serializers][0]. You can now directly specify [toJSON operations][1] instead, which you previously weren't allowed to do.

To deal with common cases, we added a new [\[Default\] extended attribute][2] which triggers the [default toJSON operation][3] that behaves similarly to how `serializers={attributes}` or `serializers={attributes, inherit}` used to. That is, it serializes all attributes that are of a [JSON type][4] into a vanilla JSON object.

It seems the following interfaces in this spec are impacted by this change:

- [ ] [`PerformanceNavigationTiming`](https://w3c.github.io/navigation-timing/#dom-performancenavigationtiming)
- [ ] [`PerformanceTiming`](https://w3c.github.io/navigation-timing/#the-performancetiming-interface) 
- [ ] [`PerformanceNavigation`](https://w3c.github.io/navigation-timing/#the-performancenavigation-interface)

All of these seem good candidate for the [default toJSON operation][3], so the below should be all you need, provided you also similarly update `PerformanceResourceTiming` and `PerformanceEntry` in their relevant specifications:

```webidl
interface PerformanceNavigationTiming : PerformanceResourceTiming {
    readonly attribute DOMHighResTimeStamp unloadEventStart;
    // etc...
    [Default] object toJSON();
};

[Exposed=Window]
interface PerformanceTiming {
    readonly attribute unsigned long long navigationStart;
    // etc...
    [Default] object toJSON();
};

[Exposed=Window]
interface PerformanceNavigation {
    const unsigned short TYPE_NAVIGATE = 0;
    // etc...
    [Default] object toJSON();
};
```

I'm sorry for the inconvenience this causes, but our hope is that this ultimately makes things a lot simpler and clearer for everybody.

Please feel free to reach out if you have any questions.

Thanks!

[0]: https://github.com/heycam/webidl/commit/a505f33
[1]: https://heycam.github.io/webidl/#idl-tojson-operation
[2]: https://heycam.github.io/webidl/#Default
[3]: https://heycam.github.io/webidl/#es-default-tojson
[4]: https://heycam.github.io/webidl/#dfn-json-types

**Comment by igrigorik** [comment]
@tobie ditto for this spec: https://github.com/w3c/resource-timing/issues/112#issuecomment-311784163

**Comment by tobie** [comment]
Yes, Respec got updated yesterday: w3c/respec#1300.

**Comment by igrigorik** [comment]
Resolved via https://github.com/w3c/navigation-timing/pull/76
