### ISSUE TITLE
Existing Test gap: Verify that toJSON is created properly

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-timing#74]
The WebIDL test verifies the existence of the method, but we've seen that sometimes properties are not serialized properly historically. We need a test for this.

**Comment by plehegar** [comment]
Fixed in https://github.com/w3c/web-platform-tests/commit/8963e7a86c3ef85f98c820f5db6c6990e2bf7395

**Comment by igrigorik** [comment]
@plehegar ditto: https://github.com/w3c/performance-timeline/issues/83#issuecomment-333640585. Does the IDL harness test the serialization?

**Comment by plehegar** [comment]
yes it does, thus my fixed :)

**Comment by igrigorik** [comment]
👍
