### ISSUE TITLE
Fix ReSpec warnings on GitHub spec

### ISSUE THREAD

**Issue by igrigorik** [w3c/navigation-timing#77]
![image](https://user-images.githubusercontent.com/10652/32398743-5b798ade-c0ae-11e7-9c68-0f8c70364503.png)

https://w3c.github.io/navigation-timing/

**Comment by igrigorik** [comment]
- There is _a lot_ of unnecessary duplication of `link-for`'s and other markup in this spec. I'm sure there is gotta be a better way to handle this. 
- We should add dependencies section, similar to what we've done in other specs — that should address https://github.com/w3c/navigation-timing/issues/65.
- Not sure on how to link PerformanceResourceTiming definition in IDL? See https://github.com/w3c/navigation-timing/issues/64.

@marcoscaceres @siusin was hoping to get to this over the weekend, alas.. looks like that's not going to happen and I'm away for next ~4 weeks. Any chance you could pick this one up?

**Comment by marcoscaceres** [comment]
Will take a look. No TPAC? 😭

**Comment by igrigorik** [comment]
@marcoscaceres I'm there (well, here.. since I'm sitting in our room already :)) today! Hope to see you in person today.

**Comment by marcoscaceres** [comment]
Ok, yeah... we got a lot of work to do on this one... needs quite a rewrite. We should just start by tidying it up.

Then we should do one section at a time. 

@siusin, could we work on this together?

**Comment by siusin** [comment]
@marcoscaceres 
Of course! There are lots of broken links to the Resource-Timing spec in the NT spec, we might need to fix the RT spec first :S
