### ISSUE TITLE
Should processing model cut the steps defined by PerformanceResourceTiming?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-timing#78]
At TPAC 2017, we realized that the steps in Navigation Timing 2 often are copies of PerformanceResourceTiming. Can we point to Resource Timing rather than having copy/paste?

**Comment by igrigorik** [comment]
The challenge is that while NT does follow the same high-level logic flow, it also instruments different sub-steps with different and additional timing attributes related to lifecycle of the document, as well as how it treats redirects — e.g. NT exposes redirectCount, whereas RT does not. In short, possible, but we can't simply defer to existing RT processing algorithm as is; we'd need to do some refactoring in both specs.

**Comment by yoavweiss** [comment]
This doesn't seem like a blocker to shipping L2. Correct?

**Comment by igrigorik** [comment]
Per the text we added to [our new charter](https://w3c.github.io/charter-webperf/)... 

> Note: after Level 2 of Navigation Timing is ratified, future development of new Navigation Timing features will be done within Resource Timing; Navigation Timing will be merged with Resource Timing.

Updated to L3.

**Comment by noamr** [comment]
> @noamr - I suspect this is obsolete.. Can we close in your opinion?

Yes
