### ISSUE TITLE
should unloaded iframes be included in their parent document's unload duration?

### ISSUE THREAD

**Issue by toddreifsteck** [w3c/navigation-timing#83]
In short, we need to test and spec language regarding the Navigation Timing durations for unload when there are multiple iFrames and a top-level navigation is made. Some early testing showed that various browsers implement this differently.

**Comment by igrigorik** [comment]
From 3/13/18 WG call: 
- need test to capture and test the unload time as defined by HTML 5 spec
- review our use of unload / pointers to HTML5 spec

Tagging as L2, unclear if this is blocker, we'll determine once we see test results.

**Comment by yoavweiss** [comment]
Discussed on the call today, and since this seems like a minor issue, we're pushing it to L3

**Comment by yoavweiss** [comment]
@noamr - Can you take a look at this and see if this is covered by your HTML integration work?
