### ISSUE TITLE
secureConnectionStart definition is inconsistent with ResourceTiming

### ISSUE THREAD

**Issue by npm1** [w3c/navigation-timing#84]
In the Navigation Timing spec, we define secureConnectionStart as follows:

- When a secure transport is used, the user agent MUST record the time as secureConnectionStart immediately before the handshake process to secure the connection.
- When a secure transport is not used, the user agent MUST set the value of secureConnectionStart to 0.

In ResourceTiming however:

- The same value as fetchStart, if a persistent connection [RFC7230] is used or the resource is retrieved from relevant application caches or local resources.
- The time immediately before the user agent starts the handshake process to secure the current connection, if a secure transport is used and the last non-redirected fetch of the resource passes the timing allow check algorithm.
- zero, otherwise.

If a connection is reused, it seems to me per the definitions that NavTiming would always return 0 whereas ResourceTiming would return fetchStart, even if the connection was not secure? I'm not sure if this discrepancy is intentional or not.

**Comment by toddreifsteck** [comment]
It seems ideal that Navigation Timing does not specify/document these and instead points to the definition in Resource Timing. If this text must stay in Navigation Timing, it should be corrected.
