### ISSUE TITLE
Should navigationEntry's navigationType be updated according to the parent page ?

### ISSUE THREAD

**Issue by shacharz** [w3c/navigation-timing#85]
I didn't see anything mentioned in https://www.w3.org/TR/navigation-timing-2/
and right now Chrome always updates navigationType to "navigate"

**Comment by igrigorik** [comment]
Can you elaborate? I'm not sure I follow what your question is.

**Comment by shacharz** [comment]
https://codepen.io/anon/pen/QxYQOZ?editors=0011

**Comment by igrigorik** [comment]
Interesting. Indeed, some quick testing on this end seems to show that NT2 implementations in Chrome and FF do not correctly set navigationType. However, Chrome seems to correctly set these values for NT1 (performance.navigation.type), whereas FF handles reload and navigate but back_forward is not reflected (guess, BF cache related). 

We need to wire up some WPT tests for this.

/cc @toddreifsteck @yoavweiss

**Comment by shacharz** [comment]
> However, Chrome seems to correctly set these values for NT1 (performance.navigation.type)

I'm on Chrome on Mac and it doesn't set NT1 correctly either

**Comment by yoavweiss** [comment]
@shacharz correct me if I'm misunderstanding your issue, but is the problem the fact when the top-level document is reloaded, that is not reflected in the iframe's navigation timing info?

@igrigorik - Chrome seems to do the right thing for NT1 for the top-level document, but not for iframes (nor for NT2)

I 100% agree that we need WPTs around this.

/cc @npm1 @tdresser

**Comment by shacharz** [comment]
> @shacharz correct me if I'm misunderstanding your issue, but is the problem the fact when the top-level document is reloaded, that is not reflected in the iframe's navigation timing info?

correct

**Comment by toddreifsteck** [comment]
Great find, @shacharz ! Thanks for sharing with us. This will be fun to fully specify in the future.

**Comment by yoavweiss** [comment]
Discussed on the call today. The right thing to do here would be to align with the HTML/Fetch definitions, so it makes sense to fix this as part of the Fetch rebase that is scheduled for L3.

**Comment by VigneshSubramaniam** [comment]
Any update on this? Need this functionality for fixing an issue. Thanks :) @yoavweiss

**Comment by yoavweiss** [comment]
@noamr - should this be resolved with Fetch integration PRs?

**Comment by noamr** [comment]
> @noamr - should this be resolved with Fetch integration PRs?

Yes (HTML PRs, not related to fetch). But perhaps some WPTs are missing for this particular issue.

**Comment by noamr** [comment]
> @shacharz correct me if I'm misunderstanding your issue, but is the problem the fact when the top-level document is reloaded, that is not reflected in the iframe's navigation timing info?

IIUC, This is the correct behavior though.
When you reload the parent page, the iframe is not "reloaded" - a new iframe is created and navigates to whichever src. The iframe is not "reloaded". Am I missing something?

**Comment by noamr** [comment]
Closing the issue.
When the container is reloaded, the iframe is not reloaded. The HTML is parsed again, and a new iframe is created. It might happen to have the same `src` as the previous iframe that was unloaded - but there is no "reload" here. The same applies for history navigations.

See https://html.spec.whatwg.org/#navigate-an-iframe-or-frame
