### ISSUE TITLE
Inconsistent implementations of navigation type in "reload the page through navigation to the same URL" scenario

### ISSUE THREAD

**Issue by jakub-g** [w3c/navigation-timing#87]
# Steps to repro:

1. Load http://example.com/
2. Focus the URL bar; don't change the URL; click enter (in short: `Alt+D`, `Enter`)
3. Execute this in console:

```
performance.getEntriesByType("navigation")[0].type
```

# Results:

- Firefox: `navigate`
- Edge: `navigate`
- Chrome: `reload`

# What spec says (emphasis mine):

> If the navigation was started by clicking on a link, or entering the URL in the user agent's address bar, or form submission, or initializing through a script operation other than the location.reload() method, let the navigation type be the DOMString "navigate".
> If the navigation was started either as a result of a meta refresh, or the location.reload() method, or _other equivalent actions_, let the navigation type be the DOMString "reload". 

Probably the discrepancy is due to the vagueness of "other equivalent actions" statement.

# Actions:

- Should a bug for Chrome be filed? (or the contrary?)
- Should the spec be clarified?

**Comment by tdresser** [comment]
This is a browser bug, tracked at crbug.com/859046.
