### ISSUE TITLE
Unload event TAO check should be for all redirects

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#95]
"If the previous document, and any HTTP redirects when navigating, pass the timing allow check algorithm, the unloadEventStart attribute MUST return a DOMHighResTimeStamp with a time value equal to the time immediately before the user agent starts the unload event of the previous document."

That language seems too lax, and we should make sure (in language and tests) that *all* redirects pass the TAO check before exposing unload.

**Comment by toddreifsteck** [comment]
I agree with the wording update that is proposed. I suspect that we'll find that the wording update is what we implement if we test this.
