### ISSUE TITLE
Define attribute behavior only once

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#97]
Currently it seems like we define each attribute behavior twice:
* Once when we talk about what the attribute means
* Once when we define the processing model for the attribute.

I think the first should be converted to a non-normative note, and the actual definition should be defined once, to avoid it getting out-of-sync.

**Comment by noamr** [comment]
Can this be closed @yoavweiss?

**Comment by yoavweiss** [comment]
Yup!
